### ISSUE TITLE
Same tool different operation

### ISSUE THREAD

**Issue by Egauss** [teodoryantcheff/SolidCam-Mach3-Post#14]
imachining same tool diferrent operation feed chanhes but cant see spindle speed changes so over lot of operations and same tool no speed changes just feed, is that postproccessor problem or is how imachining works? If i generate per operation all ok, just dont want spend time to make one file....

**Comment by teodoryantcheff** [comment]
Since obviously, I've forgotten how that works, just looked at the posts code, and spindle speeds are updated on tool change (`@start_tool` function).
Unfortunately, as of now, I can't really look into this due to workload. Feel free to fork the repo and submit a pull request.
If what you say is correct and not an issue with your mach3 configuration, you may want to take a look at the `use_solidcam_feeds` variable (`@start_of_job`).
Cheers
